name: mid_term
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/jack.jpg
