// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-cNwPsWoghlQKdqMR36QE5DC8o4HhVs',
    appId: '1:311371007032:web:c4ccf3e1aae7b96949d2cd',
    messagingSenderId: '311371007032',
    projectId: 'midtermflutter-4e159',
    authDomain: 'midtermflutter-4e159.firebaseapp.com',
    storageBucket: 'midtermflutter-4e159.appspot.com',
    measurementId: 'G-K4TPLCQG47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh4STLQxpxncZSEvE18AECG3_0KG6ekZ8',
    appId: '1:311371007032:android:f33fd3dbac3c10a849d2cd',
    messagingSenderId: '311371007032',
    projectId: 'midtermflutter-4e159',
    storageBucket: 'midtermflutter-4e159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__lwaX3GBH6D9zr5Wkn1FXKh1ulDj7G8',
    appId: '1:311371007032:ios:32b6702caf270eac49d2cd',
    messagingSenderId: '311371007032',
    projectId: 'midtermflutter-4e159',
    storageBucket: 'midtermflutter-4e159.appspot.com',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__lwaX3GBH6D9zr5Wkn1FXKh1ulDj7G8',
    appId: '1:311371007032:ios:32b6702caf270eac49d2cd',
    messagingSenderId: '311371007032',
    projectId: 'midtermflutter-4e159',
    storageBucket: 'midtermflutter-4e159.appspot.com',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk-cNwPsWoghlQKdqMR36QE5DC8o4HhVs',
    appId: '1:311371007032:web:55218ffa3662cb6949d2cd',
    messagingSenderId: '311371007032',
    projectId: 'midtermflutter-4e159',
    authDomain: 'midtermflutter-4e159.firebaseapp.com',
    storageBucket: 'midtermflutter-4e159.appspot.com',
    measurementId: 'G-NT913YPCK5',
  );
}
